-- Example SQL DDL for Orders Table
-- This file can be used with: qadmcli table create --schema example_orders.sql

-- Create Orders Table
CREATE TABLE MYLIB.ORDERS (
    ORDER_ID DECIMAL(15, 0) NOT NULL,
    CUST_ID DECIMAL(10, 0) NOT NULL,
    ORDER_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
    ORDER_STATUS CHAR(1) NOT NULL DEFAULT 'P',
    ORDER_TOTAL DECIMAL(15, 2),
    SHIPPING_ADDR VARCHAR(500),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID)
);

-- Add table description
LABEL ON TABLE MYLIB.ORDERS IS 'Customer Orders Table';

-- Add column descriptions
LABEL ON COLUMN MYLIB.ORDERS.ORDER_ID IS 'Unique order identifier';
LABEL ON COLUMN MYLIB.ORDERS.CUST_ID IS 'Customer ID reference';
LABEL ON COLUMN MYLIB.ORDERS.ORDER_DATE IS 'Order placement date';
LABEL ON COLUMN MYLIB.ORDERS.ORDER_STATUS IS 'Order status: P=Pending, C=Completed, X=Cancelled';
LABEL ON COLUMN MYLIB.ORDERS.ORDER_TOTAL IS 'Total order amount';

-- Create indexes
CREATE INDEX MYLIB.IDX_ORD_CUST ON MYLIB.ORDERS (CUST_ID);
CREATE INDEX MYLIB.IDX_ORD_DATE ON MYLIB.ORDERS (ORDER_DATE);
CREATE INDEX MYLIB.IDX_ORD_STATUS ON MYLIB.ORDERS (ORDER_STATUS, ORDER_DATE);
