-- Example SQL DDL for Orders Table
-- This file can be used with: qadmcli table create --schema example_orders.sql

-- Create Orders Table
CREATE TABLE GSLIBTST.ORDER2 (
    ORDER_ID DECIMAL(15, 0) NOT NULL,
    CUST_ID DECIMAL(10, 0) NOT NULL,
    ORDER_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
    ORDER_STATUS CHAR(1) NOT NULL DEFAULT 'P',
    ORDER_TOTAL DECIMAL(15, 2),
    SHIPPING_ADDR VARCHAR(500),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_ORDER2 PRIMARY KEY (ORDER_ID)
);

-- Add table description
LABEL ON TABLE GSLIBTST.ORDER2 IS 'Customer2 Orders Table';

-- Add column descriptions
LABEL ON COLUMN GSLIBTST.ORDER2.ORDER_ID IS 'Unique order identifier';
LABEL ON COLUMN GSLIBTST.ORDER2.CUST_ID IS 'Customer ID reference';
LABEL ON COLUMN GSLIBTST.ORDER2.ORDER_DATE IS 'Order placement date';
LABEL ON COLUMN GSLIBTST.ORDER2.ORDER_STATUS IS 'Order status: P=Pending, C=Completed, X=Cancelled';
LABEL ON COLUMN GSLIBTST.ORDER2.ORDER_TOTAL IS 'Total order amount';

-- Create indexes
CREATE INDEX GSLIBTST.IDX_ORD_CUST ON GSLIBTST.ORDER2 (CUST_ID);
CREATE INDEX GSLIBTST.IDX_ORD_DATE ON GSLIBTST.ORDER2 (ORDER_DATE);
CREATE INDEX GSLIBTST.IDX_ORD_STATUS ON GSLIBTST.ORDER2 (ORDER_STATUS, ORDER_DATE);
